# Basic Information 
title: Yifu Deng
position: Prospective Ph.D. Student
affiliation: New York University
affiliation_link: https://cs.nyu.edu/home/index.html
# affiliation_logo: ./assets/img/illinois.svg
email: yifu(dot)deng(at)nyu(dot)edu

# Search Engine Optimization (SEO)
keywords: yifu deng, deng yifu, yifudeng, dengyifu
canonical: https://yifu-deng.github.io/
description: Yifu Deng's homepage.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/
github_link: https://github.com/yifu-deng
linkedin: https://www.linkedin.com/in/yifudeng/
twitter: https://x.com/yifudeng12

# Images 
avatar: ../assets/img/avatar.jpg

# Footnotes
footnote: 
Powered by the minimal-light theme.footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: 

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
