# Basic Information 
title: Yifu Deng
position: Master's Student
affiliation: Courant Institute of Mathematical Sciences, New York University
affiliation_link: https://cs.nyu.edu/
affiliation_logo: ./assets/img/nyu-logo.svg
email: yifu(dot)deng(at)nyu(dot)edu

# Search Engine Optimization (SEO)
keywords: Yifu Deng, Intelligent Transportation Systems, Machine Learning, Computer Science
canonical: https://yifudeng.github.io
description: Yifu Deng is actively pursuing research in intelligent transportation systems, traffic prediction, and data mining.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: true

# Links
link_type: icon #text/icon
google_scholar: 
github_link: https://github.com/yifu-deng/
linkedin: https://www.linkedin.com/in/yifudeng/
twitter: https://x.com/yifudeng12

# Images 
avatar: ../assets/img/avatar.jpeg

# Footnotes
footnote: Feel free to use my website's source code.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: 

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
